export default {
  intro:
    "Cat Speak - a global community platform connecting multilingual communication and cultures worldwide",
  section1: {
    title: "1. Cat Speak's intellectual property rights",
    intro:
      "All content, technology and assets on the CAT SPEAK platform, application and website, including but not limited to:",
    items: [
      "Interface design;",
      "AI systems;",
      "Algorithms, source code;",
      "Features;",
      "Instructional documents;",
      "Databases;",
      "Trademarks, logos, images, audio data, videos in any format are the property of CAT SPEAK or its legitimate licensors.",
    ],
    note: "Users are not permitted to:",
    prohibitedItems: [
      "Copy;",
      "Redistribute;",
      "Modify;",
      "Commercially exploit;",
      "Reverse engineer;",
      "Extract data.",
    ],
    condition: "without the written consent of CAT SPEAK.",
  },
  section2: {
    title: "2. User-generated content",
    intro:
      "Users retain ownership of and bear full responsibility for content they create and publish on the CAT SPEAK platform, application and website.",
    licenseIntro:
      "By posting content, Users agree to grant CAT SPEAK a non-exclusive, worldwide, royalty-free license to:",
    licenseItems: [
      "Store;",
      "Display;",
      "Distribute within the scope of platform, application and website operations;",
      "Use for purposes of improving services.",
    ],
    commitIntro: "Users commit that uploaded content:",
    commitItems: [
      "Does not infringe copyright;",
      "Does not violate the intellectual property rights of third parties;",
      "Does not contain content contrary to Vietnamese law;",
      "Does not infringe any rights and interests of third parties.",
    ],
  },
  section3: {
    title: "3. Copyright infringement",
    intro:
      "CAT SPEAK respects intellectual property rights and will strictly handle violations.",
    noticeIntro:
      "If a User believes that content on the platform, application or website infringes their copyright, the User may submit a takedown notice accompanied by:",
    noticeItems: [
      "Information identifying the infringing content;",
      "Evidence of ownership;",
      "Contact information;",
      "A truthful statement regarding the claim, accepting full legal responsibility.",
    ],
    rightsIntro: "Cat Speak has the right to:",
    rightsItems: [
      "Remove the disputed content;",
      "Temporarily suspend the account;",
      "Terminate accounts with repeated violations.",
    ],
  },
  section4: {
    title: "4. DMCA policy (if applicable internationally)",
    text: "Cat Speak may process requests under mechanisms equivalent to the Digital Millennium Copyright Act (DMCA) or corresponding legislation in each relevant country. Those who submit false claims may face unlimited legal liability regardless of territory or country.",
  },
  section5: {
    title: "5. AI-generated content",
    items: [
      "Content generated by AI is considered to be based on aggregated data and is not intended to copy the specific content of any individual or organization.",
      "CAT SPEAK does not guarantee that AI-generated content will not partially overlap with content already available on the Internet or in public documents.",
      "Users are responsible when using AI-generated content for commercial purposes or wide publication.",
      "CAT SPEAK is fully exempt from liability for any legal disputes arising from AI-generated content or images.",
    ],
  },
  section6: {
    title: "6. Anti-piracy and account sharing",
    intro:
      "The following violations are strictly prohibited, including but not limited to:",
    items: [
      "Unauthorized recording or distribution of any paid content;",
      "Sharing accounts with third parties;",
      "Reselling or transferring access rights to third parties.",
    ],
    rightsIntro: "CAT SPEAK has the right to:",
    rightsItems: [
      "Lock accounts;",
      "Revoke access rights;",
      "Investigate, demand compensation for damages and all costs related to resolution;",
      "Work with competent State authorities to resolve the matter.",
    ],
  },
  section7: {
    title: "7. Reservation of rights",
    paragraphs: [
      "Except for rights expressly granted to Users in these Terms of Service, CAT SPEAK reserves all rights, title and interests relating to the platform, technology, content and services.",
      "CAT SPEAK's failure or delay in enforcing any right or provision shall not be deemed a waiver of that right.",
      "CAT SPEAK has the right to modify, update or discontinue part or all of its services at its discretion, in accordance with current Vietnamese law.",
    ],
  },
  section8: {
    title: "8. Contact",
    intro:
      "If you have any questions or requests related to this policy, please contact:",
    contact: {
      email: "Email:",
      website: "Website:",
      fanpage: "Fanpage:",
      hotline: "Hotline:",
    },
    copyright: "@Copyright 2026 | Cat Speak - I speak you speak we peak",
  },
}
