export { default as LandingPage } from "./LandingPage"
export { default as PolicyPage } from "./PolicyPage"
export { default as HomePage } from "./HomePage"
export { default as VideoCallRoom } from "./VideoCallRoom"
export { default as RoomDetailPage } from "./RoomDetailPage"
export { default as QueuePage } from "./QueuePage"
export { default as ComingSoonPage } from "./ComingSoonPage"
export { default as RoomsPage } from "./RoomsPage"
export { default as CatSpeakPage } from "./CatSpeakPage"

export { default as VerifyEmailPage } from "./VerifyEmailPage"
export { default as NewsPage } from "./CatSpeak/News"
export { default as DiscoverPage } from "./CatSpeak/Discover"
export { default as VideoPage } from "./CatSpeak/Video"
export { default as MailPage } from "./CatSpeak/Mail"
export { default as CatSpeakLayout } from "./CatSpeak/Layout"
